### ISSUE TITLE
Profile link issue

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/TopContributors#12]
The profile links sometimes don't show up as they should

![Screenshot 2020-05-11 at 15 26 37](https://user-images.githubusercontent.com/1009343/81567335-78421780-939c-11ea-9bb4-74ba56ea0a3a.png)

**Comment by ttoine** [comment]
maybe we can remove it, and add the link on the avatar instead ?

**Comment by Progi1984** [comment]
@NeOMakinG Is it fixed ?

**Comment by NeOMakinG** [comment]
No it's not
