### ISSUE TITLE
[IMPROVIMENT] Add contributors anchor link

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/TopContributors#22]
- It's a bit complicated to find a contributor, we sometimes have to do `CTRL + F`.
- This will allow a contributor to use this link in their CV for example.
The following url redirected to the contributor row :  

[http://contributors.prestashop.com/#PululuK](http://contributors.prestashop.com/#PululuK)

![image](https://user-images.githubusercontent.com/16455155/93194543-80460580-f748-11ea-8d75-de79e1233d9c.png)

**Comment by Progi1984** [comment]
@PululuK <3 It's so beautiful ;)
