### ISSUE TITLE
Exclude non-human profiles

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/TopContributors#45]
Is it possible to exclude non-human profiles (like bots) ?
 
- Jarvis
- Dependabot
- Dependabot Preview

I maybe forgetting some of them.

**Comment by ttoine** [comment]
what do you think @Progi1984 ? is it possible to add a filtering list ?

**Comment by PierreRambaud** [comment]
Of course we can :)

**Comment by Progi1984** [comment]
Fixed in PR : https://github.com/PrestaShop/traces/pull/13
