### ISSUE TITLE
HTTPS is not working on contributors.prestashop.com

### ISSUE THREAD

**Issue by matks** [PrestaShop/TopContributors#9]
http://contributors.prestashop.com/ ✅ 
https://contributors.prestashop.com/ 💔 

Also when HTTPS works, it would be nice to redirect HTTP on HTTPS as it's more secure

**Comment by ttoine** [comment]
who can actually manage that? @djodjo3 ?

**Comment by djodjo3** [comment]
Yep, that's already in the pipe but I can fasten things up and  have a look at it in the coming days.

**Comment by ttoine** [comment]
👍

**Comment by djodjo3** [comment]
http://contributors.prestashop.com/ ✅
https://contributors.prestashop.com/ ❤️

**Comment by matks** [comment]
> http://contributors.prestashop.com/ ✅
> https://contributors.prestashop.com/ ❤️

Did you deploy in prod on Friday ? :trollface: 

Just joking, thank you so much 🙏
