### ISSUE TITLE
GH action deploy action doesn't work

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/TopContributors#90]
There's an error deploying the website:

![image](https://user-images.githubusercontent.com/2137763/197342411-6c9892ba-1dde-4625-adc9-95d66c0183ea.png)

**Comment by kpodemski** [comment]
@Progi1984 it was working for a moment, and now it's back to the previous state

I think there are two parallel deploys now. Is that right?

**Comment by Progi1984** [comment]
It's now fixed. :tada:

**Comment by kpodemski** [comment]
thank you @Progi1984 !

@Progi1984  not a long road to top1 Franck! :D
